Create index.html.md.erb
DFE-Digital/dfe-job-descriptions pull request #61
Opened 2023-03-07 09:39 UTC by tomadams-dfe

2023-03-08 09:07 UTC, luke-slowen commented on tech-docs/source/user-research/junior-user-researcher/index.html.md.erb
> +##About the job
Needs a space between ## and the title

2023-03-08 09:09 UTC, luke-slowen requested changes
Just one minor tweak needed, as per in-line comment (space in ## header on junior UR page)

2023-03-09 16:42 UTC, duncanjbrown commented
This is fantastic @tomadams-dfe, thank you. Please could you create directories in the form `directory_name` rather than `directory-name`? Happy to help fix if this is awkward via GitHub UI!

2023-03-09 16:57 UTC, duncanjbrown approved these changes

2023-03-09 17:06 UTC, merged